# Generated by Django 5.2.1 on 2025-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0002_alter_usuarios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
