# Generated by Django 5.2.1 on 2025-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
