# Generated by Django 5.2.1 on 2025-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('marca', models.CharField(default='General', max_length=100)),
                ('referencia', models.CharField(default='General', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='General', max_length=100)),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('marca', models.CharField(default='General', max_length=100)),
                ('referencia', models.CharField(default='General', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(default='General', max_length=100)),
                ('referencia', models.CharField(default='General', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='inventario',
            name='estado',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='inventario',
            name='marca',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='inventario',
            name='referencia',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='diametro',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
