# Generated by Django 5.2.1 on 2025-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0002_categoria_estado_marca_inventario_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='diametro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
    ]
