# Generated by Django 5.2.1 on 2025-05-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_alter_inventario_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre_marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marca',
            name='referencia',
            field=models.CharField(max_length=100),
        ),
    ]
