# Generated by Django 5.2.1 on 2025-05-31 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0001_initial'),
        ('app_restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_restaurantes.restaurante'),
        ),
    ]
